version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    user: root
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "22181:2181"
    volumes:
      - /mnt/disks/sdc/kafka_storage/zookeeper:/data
      - /mnt/disks/sdc/kafka_storage/zookeeper:/datalog
      - /mnt/disks/sdc/kafka_storage/zookeeper:/logs

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    user: root
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "32181:2181"
    volumes:
      - /mnt/disks/sdc/kafka_storage/zookeeper:/data
      - /mnt/disks/sdc/kafka_storage/zookeeper:/datalog
      - /mnt/disks/sdc/kafka_storage/zookeeper:/logs

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    user: root
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "42181:2181"
    volumes:
      - /mnt/disks/sdc/kafka_storage/zookeeper:/data
      - /mnt/disks/sdc/kafka_storage/zookeeper:/datalog
      - /mnt/disks/sdc/kafka_storage/zookeeper:/logs

  kafka-1:
    image: confluentinc/cp-kafka:latest
    user: root
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://34.146.29.164:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 1000000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 100000
      KAFKA_MESSAGE_MAX_BYTES: 536870912
      KAFKA_FETCH_MAX_BYTES: 536870912
      
    volumes:
      - /mnt/disks/sdc/kafka_storage/kafka-1:/var/lib/kafka/data
      
  kafka-2:
    image: confluentinc/cp-kafka:latest
    user: root
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://:39092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://34.146.29.164:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 1000000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 100000
      KAFKA_MESSAGE_MAX_BYTES: 536870912
      KAFKA_FETCH_MAX_BYTES: 536870912
    volumes:
      - /mnt/disks/sdc/kafka_storage/kafka-2:/var/lib/kafka/data  

  kafka-3:
    image: confluentinc/cp-kafka:latest
    user: root
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

    ports:
      - 49092:49092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://:49092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://34.146.29.164:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 1000000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 100000
      KAFKA_MESSAGE_MAX_BYTES: 536870912
      KAFKA_FETCH_MAX_BYTES: 536870912
    volumes:
      - /mnt/disks/sdc/kafka_storage/kafka-3:/var/lib/kafka/data 
      