version: "2"
networks:
  kafka_net: # 세 서비스를 하나의 네트워크로 묶어줌
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"
    networks:
      - kafka_net # 세 서비스를 하나의 네트워크로 묶어줌
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - 9092:9092
      - 9999:9999
    environment:
      JMX_PORT: 9999 # JMX(Java Management Extension)를 사용할 포트 지정
      # KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote=true 
      #                 -Dcom.sun.management.jmxremote.authenticate=false 
      #                 -Dcom.sun.management.jmxremote.ssl=false 
      #                 -Djava.rmi.server.hostname=${IP} 
      #                 -Dcom.sun.management.jmxremote.rmi.port=9393 
      #                 -Djava.net.preferIPv4Stack=true
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://${IP}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      - kafka_net # 세 서비스를 하나의 네트워크로 묶어줌
    volumes:
      - C:/kafka_storage:/var/lib/kafka/data
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    depends_on:
      - kafka
      - zookeeper
    environment:
      ZK_HOSTS: "zookeeper:2181" # zookeeper 컨테이너 이름과 포트를 명시한다
      APPLICATION_SECRET: "random-secret"
    networks:
      - kafka_net # 세 서비스를 하나의 네트워크로 묶어줌