version: '2'
networks:
  kafka_net: # 세 서비스를 하나의 네트워크로 묶어줌
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    user: root
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "22181:2181"
    volumes:
      - ${LOG_DIR}/zookeeper:/data
      - ${LOG_DIR}/zookeeper:/datalog
      - ${LOG_DIR}/zookeeper:/logs
    networks:
      - kafka_net # 세 서비스를 하나의 네트워크로 묶어줌
  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    user: root
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "32181:2181"
    volumes:
      - ${LOG_DIR}/zookeeper:/data
      - ${LOG_DIR}/zookeeper:/datalog
      - ${LOG_DIR}/zookeeper:/logs
    networks:
      - kafka_net # 세 서비스를 하나의 네트워크로 묶어줌
  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    user: root
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "42181:2181"
    volumes:
      - ${LOG_DIR}/zookeeper:/data
      - ${LOG_DIR}/zookeeper:/datalog
      - ${LOG_DIR}/zookeeper:/logs
    networks:
      - kafka_net # 세 서비스를 하나의 네트워크로 묶어줌
  kafka-1:
    image: confluentinc/cp-kafka:latest
    user: root
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

    ports:
      - 29092:29092
      - 9999:9999
    environment:
      KAFKA_JMX_PORT: 9999
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://${IP}:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 100000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 60000
      KAFKA_MESSAGE_MAX_BYTES: 536870912
      KAFKA_FETCH_MAX_BYTES: 536870912
      KAFKA_NUM_NETWORK_THREADS: 10
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 10485760
    volumes:
      - ${LOG_DIR}/kafka-1:/var/lib/kafka/data
    networks:
      - kafka_net # 세 서비스를 하나의 네트워크로 묶어줌    
  kafka-2:
    image: confluentinc/cp-kafka:latest
    user: root
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

    ports:
      - 39092:39092
      - 9998:9998
    environment:
      JMX_PORT: 9998
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://:39092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://${IP}:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 100000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 60000
      KAFKA_MESSAGE_MAX_BYTES: 536870912
      KAFKA_FETCH_MAX_BYTES: 536870912
      KAFKA_NUM_NETWORK_THREADS: 10
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 10485760
    volumes:
      - ${LOG_DIR}/kafka-2:/var/lib/kafka/data  
    networks:
      - kafka_net # 세 서비스를 하나의 네트워크로 묶어줌
  kafka-3:
    image: confluentinc/cp-kafka:latest
    user: root
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

    ports:
      - 49092:49092
      - 9997:9997
    environment:
      JMX_PORT: 9997
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://:49092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://${IP}:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 100000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 60000
      KAFKA_MESSAGE_MAX_BYTES: 536870912
      KAFKA_FETCH_MAX_BYTES: 536870912
      KAFKA_NUM_NETWORK_THREADS: 10
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 10485760
    volumes:
      - ${LOG_DIR}/kafka-3:/var/lib/kafka/data 
    networks:
      - kafka_net # 세 서비스를 하나의 네트워크로 묶어줌

  kafka-4:
    image: confluentinc/cp-kafka:latest
    user: root
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

    ports:
      - 59092:59092
      - 9996:9996
    environment:
      JMX_PORT: 9996
      KAFKA_BROKER_ID: 4
      KAFKA_LISTENERS: PLAINTEXT://kafka-4:9092,PLAINTEXT_HOST://:59092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-4:9092,PLAINTEXT_HOST://${IP}:59092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 100000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 60000
      KAFKA_MESSAGE_MAX_BYTES: 536870912
      KAFKA_FETCH_MAX_BYTES: 536870912
      KAFKA_NUM_NETWORK_THREADS: 10
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 10485760
    volumes:
      - ${LOG_DIR}/kafka-4:/var/lib/kafka/data 
    networks:
      - kafka_net # 세 서비스를 하나의 네트워크로 묶어줌
  
  kafka-5:
    image: confluentinc/cp-kafka:latest
    user: root
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

    ports:
      - 19092:19092
      - 9995:9995
    environment:
      JMX_PORT: 9995
      KAFKA_BROKER_ID: 5
      KAFKA_LISTENERS: PLAINTEXT://kafka-5:9092,PLAINTEXT_HOST://:19092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-5:9092,PLAINTEXT_HOST://${IP}:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 100000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 60000
      KAFKA_MESSAGE_MAX_BYTES: 536870912
      KAFKA_FETCH_MAX_BYTES: 536870912
      KAFKA_NUM_NETWORK_THREADS: 10
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 10485760
    volumes:
      - ${LOG_DIR}/kafka-5:/var/lib/kafka/data 
    networks:
      - kafka_net # 세 서비스를 하나의 네트워크로 묶어줌
